"""Small read-only helpers shared by the executed revision notebooks."""
from functools import lru_cache
from pathlib import Path
import json,pickle
import numpy as np
import pandas as pd
from IPython.display import display,Image,Markdown
from paths import ROOT,PROCESSED,RESULTS,ADDITIONAL
import matplotlib.pyplot as plt
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'axes.spines.top':False,'axes.spines.right':False,'figure.dpi':110,'savefig.dpi':180,'svg.fonttype':'none'})
COLORS={'ADME':'#a94340','Plain':'#23658a','Baseline':'#788c4e','PCA':'#957ba7','BBB pass':'#b38242','BBB_pass':'#b38242'}
def read_json(path):return json.loads(Path(path).read_text())
@lru_cache(maxsize=2)
def dataset(strict=False):
    name='strict_exact_identity' if strict else 'audited_parent_matched'
    d=pd.read_csv(PROCESSED/(name+'.csv.gz'))
    assert d.ligand_id.is_unique
    return d.set_index('ligand_id',drop=False)
def table(relative):return pd.read_csv(RESULTS/relative)
def additional(name):return pd.read_csv(ADDITIONAL/(name+'.csv'))
def figure(relative):
    p=ROOT/relative
    display(Image(filename=str(p),width=1000))
def finish(fig,name):
    out=ROOT/'.runtime/notebook_figures';out.mkdir(parents=True,exist_ok=True)
    for ext in ['png','svg']:fig.savefig(out/(name+'.'+ext),bbox_inches='tight')
    plt.show();plt.close(fig)
def verify_model(seed,name,strict=False):
    from catboost import CatBoostRegressor
    from analysis import PROTEINS
    folder=RESULTS/('strict_identity' if strict else '')/'global_models'/f'seed{seed}'/name.replace(' ','_')
    p=pd.read_csv(folder/'test_predictions.csv');features=pd.read_csv(folder/'features.csv').feature.tolist()
    med=pd.read_csv(folder/'imputation_medians.csv',index_col=0).iloc[:,0]
    d=dataset(strict);x=d.loc[p.ligand_id,med.index].apply(pd.to_numeric,errors='coerce').fillna(med)
    if name=='PCA':
        # This transformer is generated by the included code and covered by the artifact manifest.
        with (folder/'pca.pkl').open('rb') as f:pca=pickle.load(f)
        pc=pca.transform(x[PROTEINS]);x=x.drop(columns=PROTEINS)
        for j in range(3):x[f'PC{j+1}']=pc[:,j]
    x=x[features];model=CatBoostRegressor();model.load_model(str(folder/'model.cbm'))
    pred=model.predict(x,thread_count=2)
    assert np.allclose(pred,p.prediction,atol=1e-9,rtol=1e-9)
    assert np.allclose(d.loc[p.ligand_id,'-lgLD50, mol/kg'],p.y)
    return {'seed':seed,'model':name,'strict':strict,'n_test':len(p),'max_prediction_difference':float(np.max(np.abs(pred-p.prediction))),'RMSE':float(np.sqrt(np.mean((p.y-pred)**2)))}
